version: '3.3'

services:
  code:
    image: "image_resizer"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
    depends_on:
        - redis

  redis:
    image: 'bitnami/redis:5.0'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379

  rq-worker:
    image: jaredv/rq-docker:0.0.2
    command: rq worker -u redis://rq-server:6379 high normal low